-- Converting raw IMDB basic table to usable silver table

SELECT
    b.TCONST AS TT_ID,
    b.PRIMARYTITLE AS TITLE,
    TRY_CAST(b.STARTYEAR AS INTEGER) AS RELEASE_YEAR,
    b.RUNTIMEMINUTES AS RUNTIME_MIN,
    r.AVERAGERATING AS IMDB_RATING,
    r.NUMVOTES AS NUM_VOTES
FROM BRONZE.IMDB_BASIC_IMPORT as b
    INNER JOIN BRONZE.IMDB_RATING_IMPORT as r
        ON b.TCONST = r.TCONST
WHERE b.TITLETYPE = 'movie'
    AND b.STARTYEAR IS NOT NULL
    AND b.PRIMARYTITLE IS NOT NULL
    AND b.STARTYEAR != '\\N'
    AND r.AVERAGERATING IS NOT NULL
    AND r.NUMVOTES > 1000

