-- Converting raw letterboxd table to usable silver table
SELECT
    b.ID as LB_ID,
    b.NAME AS TITLE,
    CAST(b.DATE AS INTEGER) AS RELEASE_YEAR,
    b.MINUTE AS RUNTIME_MIN,
    b.RATING AS LB_RATING,
    p.LINK AS POSTER_LINK
FROM P_MOVIE_DB.BRONZE.LETTERBOXD_BASIC_IMPORT as b
    INNER JOIN P_MOVIE_DB.BRONZE.LETTERBOXD_POSTERS_IMPORT as p
        ON b.ID = p.ID
WHERE NAME IS NOT NULL
    AND DATE IS NOT NULL
    AND RATING IS NOT NULL